version: '3.9'

services:
  text_db:
    image: postgres
    container_name: text_db_java
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: text_db
    ports:
      - '5432:5432'
    networks:
      - text-network

  app:
    image: textjava
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: text_db
      DB_HOST: text_db:5432
    depends_on:
      - text_db
    networks:
      - text-network

networks:
  text-network:
    driver: bridge
