version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - text-network

  app:
    image: weatherjava
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: postgres
      DB_HOST: db:5432
    depends_on:
      - db
    networks:
      - text-network

networks:
  text-network:
    driver: bridge
